# Generated by Django 5.1.7 on 2025-03-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_profile_college_name_profile_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='degree_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
    ]
