# Generated by Django 5.1.7 on 2025-03-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0004_profile_degree_profile_graduation_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapbook',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='scrapbookimage',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='scrapbook',
            name='images',
        ),
        migrations.AddField(
            model_name='scrapbookimage',
            name='scrapbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scrapbook_images', to='yearbook.scrapbook'),
            preserve_default=False,
        ),
    ]
